<a href="https://colab.research.google.com/github/samsara1995/leetcode/blob/master/quant_16bitlut_16bitinput_negitive.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 16-bit lut table and 16-bit input(negative number)

In [50]:
xmin=-1.
xmax=2.
xzero=0

In [51]:
import numpy as np

In [52]:
s=np.linspace(xmin,xmax,256)

In [35]:
s

array([-1.        , -0.98823529, -0.97647059, -0.96470588, -0.95294118,
       -0.94117647, -0.92941176, -0.91764706, -0.90588235, -0.89411765,
       -0.88235294, -0.87058824, -0.85882353, -0.84705882, -0.83529412,
       -0.82352941, -0.81176471, -0.8       , -0.78823529, -0.77647059,
       -0.76470588, -0.75294118, -0.74117647, -0.72941176, -0.71764706,
       -0.70588235, -0.69411765, -0.68235294, -0.67058824, -0.65882353,
       -0.64705882, -0.63529412, -0.62352941, -0.61176471, -0.6       ,
       -0.58823529, -0.57647059, -0.56470588, -0.55294118, -0.54117647,
       -0.52941176, -0.51764706, -0.50588235, -0.49411765, -0.48235294,
       -0.47058824, -0.45882353, -0.44705882, -0.43529412, -0.42352941,
       -0.41176471, -0.4       , -0.38823529, -0.37647059, -0.36470588,
       -0.35294118, -0.34117647, -0.32941176, -0.31764706, -0.30588235,
       -0.29411765, -0.28235294, -0.27058824, -0.25882353, -0.24705882,
       -0.23529412, -0.22352941, -0.21176471, -0.2       , -0.18

In [55]:
index=np.argwhere(s == 0)

In [56]:
index

array([[85]])

In [36]:
value=np.exp(s)

In [37]:
value

array([0.36787944, 0.37223299, 0.37663807, 0.38109527, 0.38560522,
       0.39016854, 0.39478587, 0.39945784, 0.40418509, 0.40896829,
       0.4138081 , 0.41870518, 0.42366021, 0.42867389, 0.43374689,
       0.43887993, 0.44407371, 0.44932896, 0.4546464 , 0.46002677,
       0.46547081, 0.47097928, 0.47655294, 0.48219255, 0.4878989 ,
       0.49367279, 0.499515  , 0.50542635, 0.51140766, 0.51745975,
       0.52358347, 0.52977965, 0.53604916, 0.54239286, 0.54881164,
       0.55530637, 0.56187797, 0.56852734, 0.57525539, 0.58206307,
       0.58895131, 0.59592107, 0.60297331, 0.610109  , 0.61732914,
       0.62463473, 0.63202677, 0.63950629, 0.64707432, 0.65473192,
       0.66248014, 0.67032005, 0.67825274, 0.6862793 , 0.69440086,
       0.70261852, 0.71093344, 0.71934675, 0.72785963, 0.73647326,
       0.74518882, 0.75400752, 0.76293058, 0.77195924, 0.78109475,
       0.79033836, 0.79969137, 0.80915506, 0.81873075, 0.82841976,
       0.83822343, 0.84814312, 0.8581802 , 0.86833606, 0.87861

In [38]:
vmax=value.max()

In [39]:
vmax

7.38905609893065

In [13]:
vmin=value.min()

In [14]:
vmin

0.36787944117144233

In [40]:
scale=(256*256-1)/vmax

In [41]:
scale

8869.197786911413

In [42]:
qvalue=scale*value

In [43]:
qvalue

array([ 3262.79552549,  3301.40804229,  3340.47750666,  3380.00932619,
        3420.00897247,  3460.48198186,  3501.43395621,  3542.87056369,
        3584.79753954,  3627.22068686,  3670.14587743,  3713.57905253,
        3757.52622374,  3801.99347378,  3846.98695736,  3892.51290203,
        3938.57760902,  3985.18745414,  4032.34888867,  4080.06844021,
        4128.35271361,  4177.20839191,  4226.64223721,  4276.66109163,
        4327.2718783 ,  4378.48160224,  4430.29735138,  4482.72629754,
        4535.77569741,  4589.45289353,  4643.76531538,  4698.72048033,
        4754.32599471,  4810.58955488,  4867.51894828,  4925.12205449,
        4983.40684635,  5042.38139107,  5102.05385129,  5162.43248628,
        5223.52565304,  5285.34180747,  5347.88950553,  5411.17740445,
        5475.2142639 ,  5540.00894721,  5605.57042261,  5671.90776446,
        5739.0301545 ,  5806.94688313,  5875.66735071,  5945.20106882,
        6015.55766163,  6086.74686717,  6158.77853874,  6231.66264625,
      

In [44]:
lut=qvalue.astype(np.uint16)

In [45]:
lut

array([ 3262,  3301,  3340,  3380,  3420,  3460,  3501,  3542,  3584,
        3627,  3670,  3713,  3757,  3801,  3846,  3892,  3938,  3985,
        4032,  4080,  4128,  4177,  4226,  4276,  4327,  4378,  4430,
        4482,  4535,  4589,  4643,  4698,  4754,  4810,  4867,  4925,
        4983,  5042,  5102,  5162,  5223,  5285,  5347,  5411,  5475,
        5540,  5605,  5671,  5739,  5806,  5875,  5945,  6015,  6086,
        6158,  6231,  6305,  6380,  6455,  6531,  6609,  6687,  6766,
        6846,  6927,  7009,  7092,  7176,  7261,  7347,  7434,  7522,
        7611,  7701,  7792,  7884,  7978,  8072,  8168,  8264,  8362,
        8461,  8561,  8662,  8765,  8869,  8974,  9080,  9187,  9296,
        9406,  9517,  9630,  9744,  9859,  9976, 10094, 10214, 10334,
       10457, 10580, 10706, 10832, 10961, 11090, 11222, 11354, 11489,
       11625, 11762, 11901, 12042, 12185, 12329, 12475, 12623, 12772,
       12923, 13076, 13231, 13387, 13546, 13706, 13868, 14032, 14199,
       14367, 14537,

In [46]:
a=-1000

In [69]:
h8=int(a/256)+index
#l8=a-(h8-index)*256

In [70]:
lut[82]

8561

In [71]:
h8

array([[82]])

In [64]:
lut[82]+(lut[83]-lut[82])*l8/256

array([[8469.46875]])

In [72]:
lut[82]

8561